-- Migration: Criar tabela projetosderesolucao
-- Data: 2026-01-05

CREATE TABLE IF NOT EXISTS "public"."projetosderesolucao" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "documento_id" bigint NOT NULL,
    "ementa" text,
    "corpo_texto" text,
    "justificativa" text,
    CONSTRAINT "projetosderesolucao_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "projetosderesolucao_documento_id_fkey" FOREIGN KEY ("documento_id") REFERENCES "public"."documentos"("id") ON DELETE CASCADE
);

-- Permissões (iguais às outras tabelas)
ALTER TABLE "public"."projetosderesolucao" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."projetosderesolucao" TO "anon";
GRANT ALL ON TABLE "public"."projetosderesolucao" TO "authenticated";
GRANT ALL ON TABLE "public"."projetosderesolucao" TO "service_role";

CREATE POLICY "Leitura pública" ON "public"."projetosderesolucao" FOR SELECT USING (true);
CREATE POLICY "Escrita autenticada" ON "public"."projetosderesolucao" FOR ALL USING ((auth.role() = 'authenticated'::text));
