// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itjlzbnrdileuapsqwwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0amx6Ym5yZGlsZXVhcHNxd3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODY5ODMsImV4cCI6MjA2NjA2Mjk4M30.yt3_3gtSO9Xs9wgD2b-ysLCQH7o9P5fdG4Yw1UuDV7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);